const aboutMe = [
    { id: 1, title: "Frontend, to fit your needs", content: "I can develop beautiful and responsive interfaces for your projects with performance, usability and accessibility for your customers. My knowledge on modern tech stacks can help your projects to improve in size, reliability and efficiency.", image: "/assets/img/aboutme/frontend.png" },
    { id: 2, title: "Backend to solve your problems", content: "I can build APIs, microservices and integrations with external services, aiming for security, performance, effectiveness and response time for your services. My knowledge on modern tech stacks can help your projects to improve in size, reliability and efficiency.", image: "/assets/img/aboutme/backend.png" },
    { id: 3, title: "Mobile, to access in the palm of your hand", content: "I can develop mobile applications with great usability, so your users can access your services when, and where he want with ease.", image: "/assets/img/aboutme/mobile.png" },
    { id: 4, title: "Two's company, three's a Fullstack!", content: "Imagine a jack of all trades working for/with you. Don't need to imagine anymore, you've found him!", image: "/assets/img/aboutme/fullstack.png" },
    { id: 5, title: "Don't forget to store your data", content: "Data is one of the most important things to have. So it's good to make sure your data is stored in a safe, structured and organized way. I can help create and maintain SQL/NoSQL databases, so your company understands your customers' needs.", image: "/assets/img/aboutme/database.png" },
    { id: 6, title: "DevOps, so you can be online 24/7", content: "In nowdays, it's nice to automate as much processes as you can. I can help you to develop and mantain provisioning and pipelines so all your workflow won't need as much human hands as it should have.", image: "/assets/img/aboutme/devops.png" },
    { id: 7, title: "Scalability, while saving every penny", content: "Hosting and scalability are difficult or costy? Not anymore! Believe me! It's possible to have your services in cloud, with ease, integrating with a ecosystem of cloud services, while whitin your budget! Show your project to the whole world, and conquer more customers!", image: "/assets/img/aboutme/cloud.png" },
    { id: 8, title: "Less Artificial and more Intelligence", content: "Have you ever thought about implementing artificial intelligence in your products and services? Did you know it's easier than you think? Using third-party services, and techniques like Machine Learning and Deep Learning, we can build products with super powers!", image: "/assets/img/aboutme/ai.png" },
    { id: 9, title: "It's faster to grow with mentorship", content: "Everyone has a beginning, but not everyone has to go through difficult steps. With mentoring, it becomes easier to achieve your goals more quickly and effectively, design and implement projects and follow the most appropriate paths for your career.", image: "/assets/img/aboutme/mentor.png" },
    { id: 10, title: "Need a speaker? You've found him!", content: "It's always good to discover new things. And lectures are a great way to obtain information in a quick and didactic way, to be up to date with the latest developments in the world of technology, careers and professional relationships.", image: "/assets/img/aboutme/speaker.png" },
];

export default aboutMe;