const events = [
    { id: 1, title: "Technology week 2022 - Etec de Embu", type: 'video', url: 'https://www.youtube.com/embed/kctaSppwQb4?si=L7Gmg3aw_jTFQE3R', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, maxime nihil. Doloremque sapiente nesciunt hic non ducimus saepe repellendus animi est? Sequi nihil autem voluptatum magnam dolores magni minima id.' },
    { id: 2, title: "Technology week 2022 - Etec de Embu", type: 'video', url: 'https://www.youtube.com/embed/kctaSppwQb4?si=oD9I6cnuuZbWlreD&amp;start=9851', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, maxime nihil. Doloremque sapiente nesciunt hic non ducimus saepe repellendus animi est? Sequi nihil autem voluptatum magnam dolores magni minima id.' },
    { id: 3, title: "Modern web development at Etecs", type: 'video', url: 'https://www.youtube.com/embed/P5em8ruWw24?si=ZLHZxIG2Ea_6EzUo&amp;start=451', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, maxime nihil. Doloremque sapiente nesciunt hic non ducimus saepe repellendus animi est? Sequi nihil autem voluptatum magnam dolores magni minima id.' },
    { id: 4, title: "Starting at IT field: First steps, market and career", type: 'video', url: 'https://www.youtube.com/embed/WKs0ZG4j-20?si=G5y5mZb2XnrBh5-a&amp;start=182', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, maxime nihil. Doloremque sapiente nesciunt hic non ducimus saepe repellendus animi est? Sequi nihil autem voluptatum magnam dolores magni minima id.' },
    { id: 5, title: "Technology week 2021 - Etec de Embu", type: 'video', url: 'https://www.youtube.com/embed/MgR1IVrwqwA?si=k4o0gIv-ECIKWRoB&amp;start=196', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, maxime nihil. Doloremque sapiente nesciunt hic non ducimus saepe repellendus animi est? Sequi nihil autem voluptatum magnam dolores magni minima id.' },
    { id: 6, title: "Developer Week at Campus Party 2019", type: 'video', url: 'https://www.youtube.com/embed/CtUouGdSw_w?si=_2AzbY858yTZTFYW&amp;start=12980', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, maxime nihil. Doloremque sapiente nesciunt hic non ducimus saepe repellendus animi est? Sequi nihil autem voluptatum magnam dolores magni minima id.' },
    { id: 7, title: "Hackathon 2022/1 - Fatec Zona Sul", type: 'video', url: 'https://www.youtube.com/embed/NwMJ5tRNliE?si=vJhItif9hxOatjq2', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, maxime nihil. Doloremque sapiente nesciunt hic non ducimus saepe repellendus animi est? Sequi nihil autem voluptatum magnam dolores magni minima id.' },
    { id: 8, title: "Hackathon 2022/2 - Fatec Zona Sul", type: 'video', url: 'https://www.youtube.com/embed/FuGPFWBGCxY?si=REC_CQqxo7QGwQMJ', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, maxime nihil. Doloremque sapiente nesciunt hic non ducimus saepe repellendus animi est? Sequi nihil autem voluptatum magnam dolores magni minima id.' },
];

export default events;