const events = [
    { id: 1, title: "Technology week 2022/1 - Etec de Embu", type: 'video', url: 'https://www.youtube.com/embed/kctaSppwQb4?si=L7Gmg3aw_jTFQE3R', content: 'Lecture about distributed cloud systems, for teachers and students at Etec de Embu. The event had an average audience of 200 people.' },
    { id: 2, title: "Technology week 2022/2 - Etec de Embu", type: 'video', url: 'https://www.youtube.com/embed/kctaSppwQb4?si=oD9I6cnuuZbWlreD&amp;start=9851', content: 'Lecture about modern web development, for teachers and students at Etec de Embu. The event had an average audience of 200 people.' },
    { id: 3, title: "Modern web development at Etecs", type: 'video', url: 'https://www.youtube.com/embed/P5em8ruWw24?si=ZLHZxIG2Ea_6EzUo&amp;start=451', content: 'Lecture about modern web development, for teachers and students at various institutions simultaneously. The event had an average audience of 400 people.' },
    { id: 4, title: "Starting at IT field: First steps, market and career", type: 'video', url: 'https://www.youtube.com/embed/WKs0ZG4j-20?si=G5y5mZb2XnrBh5-a&amp;start=182', content: 'Lecture about Starting at IT field: First steps, market and career, for teachers and students at Fatec Osasco. The event had an average audience of 120 people.' },
    { id: 5, title: "Technology week 2021 - Etec de Embu", type: 'video', url: 'https://www.youtube.com/embed/MgR1IVrwqwA?si=k4o0gIv-ECIKWRoB&amp;start=196', content: 'Lecture about The IT professional of the "new normal", for teachers and students at Etec de Embu. The event had an average audience of 200 people.' },
    { id: 6, title: "Developer Week at Campus Party 2019", type: 'video', url: 'https://www.youtube.com/embed/CtUouGdSw_w?si=_2AzbY858yTZTFYW&amp;start=12980', content: 'Lecture about Embedded Software Development at educational environments, at Campus Party 13 (2019). The event had an average audience of 300 people.' },
    { id: 7, title: "Hackathon 2nd edition - Fatec Zona Sul", type: 'video', url: 'https://www.youtube.com/embed/NwMJ5tRNliE?si=vJhItif9hxOatjq2', content: 'Hackathon organized and executed to promote a practical and immersive experience in product development. An average of 160 people participated.' },
    { id: 8, title: "Hackathon 3rd edition - Fatec Zona Sul", type: 'video', url: 'https://www.youtube.com/embed/FuGPFWBGCxY?si=REC_CQqxo7QGwQMJ', content: 'Hackathon organized and executed to promote a practical and immersive experience in product development. An average of 160 people participated.' },
];

export default events;