const projects = [
    { id: 1, title: "The first ChatGPT plugin with news and content in portuguese", image: '/assets/img/projects/gpt.png', content: 'I helped to develop the first plugin for ChatGPT to disseminate news with content in Portuguese, increasing the reach of content produced by the company, using innovative technologies, with the adoption of use by hundreds of thousands of users in the first days in production.', website: 'https://economia.uol.com.br/noticias/redacao/2023/10/16/ia-uol-cria-plugin-no-chatgpt-para-busca-de-noticias-do-brasil.htm', github: { Frontend: '', Backend: '', Mobile: '', Desktop: '' } },
    { id: 2, title: "Etec de Embu's website", image: '/assets/img/projects/etec.png', content: 'The Etec de Embu website was developed to facilitate registration for entrance exams, and to access information about the institution, courses offered and teaching staff. The website has all the features to facilitate contact between the academic institution and people interested in taking the courses offered. It has a CMS made by scratch, to allow users to publish new content when necessary.', website: 'https://etecdeembu.com.br', github: { Frontend: '', Backend: '', Mobile: '', Desktop: '' } },
    { id: 3, title: "Secplan", image: '/assets/img/projects/secplan.png', content: 'Secplan is an application for aggregating insurance plans and insurers. Through it, the user is able to search for insurance plans of the most varied types (health, life, property, automobile) and filter by the details that each plan offers. The application has the functionality that sets it apart compared to equivalent applications: it allows the user to customize insurance, so that they can more easily negotiate their interests with the insurance company.', website: '', github: { Frontend: '', Backend: '', Mobile: 'https://github.com/lucasluzdev/secplan.git', Desktop: '' } },
    { id: 4, title: "DOLL-Y", image: '/assets/img/projects/dolly.png', content: "DOLL-Y is a clone of Open AI's DALL-E. This project makes use of artificial intelligence services from OpenAI, to generate customized images through prompts provided by the user.", website: 'https://doll-y-luluzdev.vercel.app/', github: { Frontend: 'https://github.com/lucasluzdev/DOLL-Y-frontend', Backend: 'https://github.com/lucasluzdev/DOLL-Y-backend', Mobile: '', Desktop: '' } },
    { id: 5, title: "Omnistack", image: '/assets/img/projects/omnistack.png', content: 'Omnistack is an AirBnB clone. This project has a frontend, backend and mobile connected via a websocket, and it is possible to register users and rent properties.', website: '', github: { Frontend: 'https://github.com/lucasluzdev/omnistack9-frontend', Backend: 'https://github.com/lucasluzdev/omnistack9-backend', Mobile: 'https://github.com/lucasluzdev/omnistack9-mobile', Desktop: '' } },
    { id: 6, title: "Tuxmotion (WIP)", image: '/assets/img/projects/tuxmotion.png', content: 'Tuxmotion will be a FOSS alternative to genymotion. It will be software for emulating Android devices, to assist in application development and for general use. This project will make use of the most advanced features of current operating systems, to provide a better user and development experience.', website: '', github: { Frontend: '', Backend: '', Mobile: '', Desktop: 'https://github.com/lucasluzdev/tuxmotion.git' } },
    { id: 7, title: "Financial Buddy (WIP)", image: '/assets/img/projects/buddy.png', content: 'Financial Buddy will be a finance and investment control ecosystem to help users control their costs and investments. It will be a project aimed at usability and ease so that people can more easily control their finances and control their investments.', website: '', github: { Frontend: 'https://github.com/lucasluzdev/finnancial-buddy-frontend.git', Backend: 'https://github.com/lucasluzdev/finnancial-buddy-backend.git', Mobile: 'https://github.com/lucasluzdev/finnancial-buddy-mobile.git', Desktop: '' } },
    { id: 8, title: "MixList (WIP)", image: '/assets/img/projects/play.png', content: 'MixList is a project to centralize the creation and modification of your playlists. For people who listen to music and podcasts on different platforms and want to standardize their playlists, the project will have integration with the main audio and video streaming platforms.', website: '', github: { Frontend: 'https://github.com/lucasluzdev/mixlist-frontend.git', Backend: 'https://github.com/lucasluzdev/mixlist-backend', Mobile: 'https://github.com/lucasluzdev/mixlist-mobile', Desktop: '' } },
];

export default projects;