const stack = [
    { id: 1, name: 'HTML5', image: '/assets/img/dev/html.png', tags: ['main', 'frontend'] },
    { id: 2, name: 'CSS3', image: '/assets/img/dev/css.png', tags: ['main', 'frontend'] },
    { id: 3, name: 'Javascript', image: '/assets/img/dev/javascript.png', tags: ['main', 'frontend'] },
    { id: 4, name: 'NodeJs', image: '/assets/img/dev/nodejs.png', tags: ['main', 'backend'] },
    { id: 5, name: 'ReactJs', image: '/assets/img/dev/react.png', tags: ['main', 'frontend'] },
    { id: 6, name: 'ReactNative', image: '/assets/img/dev/reactnative.png', tags: ['main', 'frontend'] },
    { id: 7, name: 'Postgres', image: '/assets/img/dev/postgresql.png', tags: ['main', 'database'] },
    { id: 8, name: 'MongoDB', image: '/assets/img/dev/mongodb.png', tags: ['main', 'database'] },
    { id: 9, name: 'NextJs', image: '/assets/img/dev/nextjs.png', tags: ['frontend'] },
    { id: 10, name: 'VueJs', image: '/assets/img/dev/vue.png', tags: ['frontend'] },
    { id: 11, name: 'Redux', image: '/assets/img/dev/redux.png', tags: ['frontend'] },
    { id: 12, name: 'JQuery', image: '/assets/img/dev/jquery.png', tags: ['frontend'] },
    { id: 13, name: 'Golang', image: '/assets/img/dev/golang.png', tags: ['backend'] },
    { id: 14, name: 'Python', image: '/assets/img/dev/python.png', tags: ['backend'] },
    { id: 15, name: 'PHP', image: '/assets/img/dev/php.png', tags: ['backend'] },
    { id: 16, name: 'Laravel', image: '/assets/img/dev/laravel.png', tags: ['backend'] },
    { id: 17, name: 'Java', image: '/assets/img/dev/java.png', tags: ['backend'] },
    { id: 18, name: 'Kotlin', image: '/assets/img/dev/kotlin.png', tags: ['mobile'] },
    { id: 19, name: 'MySQL', image: '/assets/img/dev/mysql.png', tags: ['database'] },
    { id: 20, name: 'Tailwild', image: '/assets/img/dev/tailwind.png', tags: ['frontend'] },
    { id: 21, name: 'Bootstrap', image: '/assets/img/dev/bootstrap.png', tags: ['frontend'] },
    { id: 22, name: 'SASS', image: '/assets/img/dev/sass.png', tags: ['frontend'] },
    { id: 23, name: 'Jest', image: '/assets/img/dev/jest.png', tags: ['main', 'testing'] },
    { id: 24, name: 'Mocha', image: '/assets/img/dev/mocha.png', tags: ['testing'] },
    { id: 25, name: 'Vitest', image: '/assets/img/dev/vitest.png', tags: ['testing'] },
    { id: 26, name: 'Cypress', image: '/assets/img/dev/cypress.png', tags: ['main', 'testing'] },
    { id: 27, name: 'Selenium', image: '/assets/img/dev/selenium.png', tags: ['testing'] },
    { id: 28, name: 'Puppeteer', image: '/assets/img/dev/puppeteer.png', tags: ['testing'] },
    { id: 29, name: 'Git', image: '/assets/img/dev/git.png', tags: ['main', 'tools'] },
    { id: 30, name: 'Linux', image: '/assets/img/dev/linux.png', tags: ['main', 'tools'] },
    { id: 31, name: 'ElasticSearch', image: '/assets/img/dev/elasticsearch.png', tags: ['tools'] },
    { id: 32, name: 'Redis', image: '/assets/img/dev/redis.png', tags: ['tools'] },
    { id: 33, name: 'Docker', image: '/assets/img/dev/docker.png', tags: ['main', 'tools', 'devops'] },
    { id: 34, name: 'Kubernetes', image: '/assets/img/dev/kubernetes.png', tags: ['main', 'tools', 'CI/CD', 'devops'] },
    { id: 35, name: 'Jenkins', image: '/assets/img/dev/jenkins.png', tags: ['main', 'tools', 'CI/CD', 'devops'] },
    { id: 36, name: 'Grafana', image: '/assets/img/dev/grafana.png', tags: ['tools', 'monitoring', 'devops'] },
    { id: 37, name: 'Prometheus', image: '/assets/img/dev/prometheus.png', tags: ['tools', 'monitoring', 'devops'] },
    { id: 38, name: 'Kibana', image: '/assets/img/dev/kibana.png', tags: ['main', 'tools', 'monitoring', 'devops'] },
    { id: 39, name: 'AWS', image: '/assets/img/dev/aws.png', tags: ['main', 'cloud', 'devops'] },
    { id: 40, name: 'GCP', image: '/assets/img/dev/gcp.png', tags: ['cloud', 'devops'] },
    { id: 41, name: 'Vercel', image: '/assets/img/dev/vercel.png', tags: ['cloud', 'devops'] },
    { id: 42, name: 'Terraform', image: '/assets/img/dev/terraform.png', tags: ['provisioning', 'devops'] },
];

export default stack;